// <auto-generated />
namespace ProjectsTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Project_PTask_Comment_Metric_initModelsStructure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Project_PTask_Comment_Metric_initModelsStructure));
        
        string IMigrationMetadata.Id
        {
            get { return "201611290923308_Project_PTask_Comment_Metric_initModelsStructure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
