// <auto-generated />
namespace ProjectsTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class PTAdministrator_user_add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PTAdministrator_user_add));
        
        string IMigrationMetadata.Id
        {
            get { return "201611281059477_PTAdministrator_user_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
