// <auto-generated />
namespace ProjectsTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ProjectTasks_cascadeDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProjectTasks_cascadeDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201612061853303_ProjectTasks_cascadeDelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
