// <auto-generated />
namespace ProjectsTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class TimeReportItem_deletedReportedOn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TimeReportItem_deletedReportedOn));
        
        string IMigrationMetadata.Id
        {
            get { return "201612061542520_TimeReportItem_deletedReportedOn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
