// <auto-generated />
namespace ProjectsTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FirstNameLastNameForUser_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstNameLastNameForUser_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201611281434221_FirstNameLastNameForUser_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
