// <auto-generated />
namespace ProjectsTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ExpectedEndDate_project_madeRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExpectedEndDate_project_madeRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201611301233325_ExpectedEndDate_project_madeRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
